server: hub-cloud.browserstack.com
user: ryanheneise2
key: JsLydzFEfW2nJv7yzFHw

common_caps:
  build: capybara-browserstack
  browserstack.debug: true

browser_caps:
  - browser: chrome
    browserstack.local: true
